name: Go

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  merge_group:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Test
        run: go test -race -v ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Check Go module
        run: |
          go mod tidy
          git diff --exit-code -- go.sum go.mod
      - name: Check Go vet
        run: go vet ./...
      - name: Check static analysis
        # https://github.com/dominikh/go-tools/releases/tag/2024.1.1
        run: go run honnef.co/go/tools/cmd/staticcheck@56172d41b117cc2c2f99f65fe0a790c8d7d7ea66 ./...